---
- name: Harbor | Get docker-registry.service LoadState and save to variable
  command: systemctl show docker-registry.service -p LoadState --value
  register: docker_registry_install_LoadState

- include_tasks: install.yaml
  when: .docker_registry_install_LoadState.stdout | eq "not-found"

- name: DockerRegistry | Wait for registry service to become available
  command: |
    if ! timeout 300 bash -c 'while ! nc -zv localhost 443; do sleep 2; done'; then
        echo "ERROR: Docker Registry did not start within 5 minutes!"
        exit 1
    fi  
