- name: Image | Ensure container images is available
  image:
    copy:
      from:
        path: >-
          {{ .binary_dir }}/images/
        manifests: "{{ .download.images.manifests | toJson }}"
      to:
        path: >-
          {{ .artifact_dir }}/images/
  when:
    - .download.images.manifests | default list | empty | not
