---
- name: Package | Reset artifact directory
  command: |
    rm -rf {{ .artifact_dir }} && mkdir -p {{ .artifact_dir }}

- name: Package | Copy required binaries and images
  block:
    # Download core binaries
    - include_tasks: binary.yaml
    # Download Helm and CNI binaries
    - include_tasks: helm.yaml
    # Download remote images to the local images directory
    - include_tasks: images.yaml
    # Download iso file
    - include_tasks: iso.yaml

- name: Package | Export artifact
  command: |
    cp {{ .work_dir }}/manifests.yaml {{ .artifact_dir }}/manifests.yaml
    {{- if .download.artifact_file | empty }}
    artifact_file={{ .work_dir }}/artifact.tgz
    {{- else }}
    artifact_file={{ .download.artifact_file }}
    {{- end }}
    cd {{ .artifact_dir }} && tar -czvf $artifact_file .
