---
- name: Pre | Run Pre-Installation Scripts
  hosts:
    - all
  tasks:
    - name: Pre | Copy global pre-installation script to remote hosts
      when: (print "%s/pre_install.sh" .scripts_dir) | fileExists
      copy:
        src: >-
          {{ .scripts_dir }}/pre_install.sh
        dest: >-
          /etc/kubekey/scripts/pre_install.sh
        mode: 0755

    - name: Pre | Copy group pre-installation scripts to remote hosts
      copy:
        src: >-
          {{ .scripts_dir }}/{{ .item }}/pre_install.sh
        dest: >-
          /etc/kubekey/scripts/pre_install_group_{{ .item }}.sh
        mode: 0755
      loop: "{{ .pre_install_groups | default list | toJson }}"
      when:
        - (getStringSlice .groups .item) | default list | has .inventory_hostname
        - (print "%s/%s/pre_install.sh" .scripts_dir .item) | fileExists

    - name: Pre | Copy node-specific pre-installation script to remote hosts
      when: (print "%s/pre_install_%s.sh" .scripts_dir .inventory_hostname) | fileExists
      copy:
        src: >-
          {{ .scripts_dir }}/pre_install_{{ .inventory_hostname }}.sh
        dest: >-
          /etc/kubekey/scripts/pre_install_{{ .inventory_hostname }}.sh
        mode: 0755

    - name: Pre | Execute global pre-installation script on remote hosts
      when: (print "%s/pre_install.sh" .scripts_dir) | fileExists
      command: /etc/kubekey/scripts/pre_install.sh

    - name: Pre | Execute group pre-installation scripts in defined order
      command: |
        for group in {{ .pre_install_groups | default list | join " " }}; do
          file="/etc/kubekey/scripts/pre_install_group_${group}.sh"
          if [ -f "$file" ]; then
            chmod +x "$file"
            "$file"
          fi
        done

    - name: Pre | Execute node-specific pre-installation script on remote hosts
      when: (print "%s/pre_install_%s.sh" .scripts_dir .inventory_hostname) | fileExists
      command: /etc/kubekey/scripts/pre_install_{{ .inventory_hostname }}.sh
