apiVersion: apps/v1
kind: Deployment
metadata:
  name: capkk-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-kk
      app: capkk-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        cluster.x-k8s.io/provider: infrastructure-kk
        app: capkk-controller-manager
    spec:
      containers:
      - name: manager
        image: capkk-controller-manager-image
        imagePullPolicy: IfNotPresent
        command:
          - controller-manager
          - --leader-election
          - --leader-election-id=controller-leader-election-capkk
          - --v=4
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1024Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9440
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9440
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: capkk
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      