dependencies:
  # Initialize new Kubernetes nodes
  - role: native/repository
    when:
      - or (.groups.k8s_cluster | default list | has .inventory_hostname) (.groups.image_registry | default list | has .inventory_hostname)
  # install nfs for nfs nodes
  - role: native/nfs
    when: .groups.nfs | default list | has .inventory_hostname
  # Always perform initialization steps for all nodes
  - role: native/ntp
    when:
      - or (.groups.k8s_cluster | default list | has .inventory_hostname) (.groups.image_registry | default list | has .inventory_hostname)
  - role: native/init
  - role: native/dns


