FROM ubuntu:18.04 as ubuntu1804
ARG TARGETARCH
ARG OS_RELEASE=bionic
ARG DIR=ubuntu-18.04-${TARGETARCH}-debs
ARG PKGS=".common[],.debs[]"
ARG BUILD_TOOLS="apt-transport-https software-properties-common ca-certificates curl wget gnupg dpkg-dev genisoimage"
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN dpkg --get-selections | grep -v deinstall | cut -f1 | cut -d ':' -f1 > packages.list

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends ca-certificates apt-transport-https curl wget gnupg \
 && sed -i 's|http://archive.ubuntu.com/ubuntu/|https://mirrors.huaweicloud.com/ubuntu/|g' /etc/apt/sources.list \
 && sed -i 's|http://security.ubuntu.com/ubuntu/|https://mirrors.huaweicloud.com/ubuntu/|g' /etc/apt/sources.list \
 && apt-get update -qq \
 && apt-get install -y --no-install-recommends software-properties-common dpkg-dev genisoimage \
 && add-apt-repository ppa:gluster/glusterfs-7 -y || true \
 && curl -fsSL https://mirrors.huaweicloud.com/docker-ce/linux/ubuntu/gpg | apt-key add - \
 && echo "deb [arch=${TARGETARCH}] https://mirrors.huaweicloud.com/docker-ce/linux/ubuntu ${OS_RELEASE} stable" > /etc/apt/sources.list.d/docker.list \
 && apt-get update -qq

WORKDIR /package
COPY packages.yaml .

COPY --from=mikefarah/yq:4.11.1 /usr/bin/yq /usr/bin/yq
RUN yq eval "${PKGS}" packages.yaml >> packages.list \
    && dpkg --get-selections | grep -v deinstall | cut -f1 | cut -d ':' -f1 >> packages.list \
    && sort -u packages.list | xargs apt-get install --yes --reinstall --print-uris \
       | awk -F "'" '{print $2}' | grep -v '^$' | sort -u > packages.urls

RUN mkdir -p ${DIR} \
    && wget -q -x -P ${DIR} -i packages.urls \
    && cd ${DIR} \
    && dpkg-scanpackages ./ /dev/null | gzip -9c > ./Packages.gz

RUN genisoimage -r -o ${DIR}.iso ${DIR}

FROM scratch
COPY --from=ubuntu1804 /package/*.iso /
