---
- hosts:
    - all
  gather_facts: true
  roles:
    - native/root
# Load default variables and perform prechecks on all hosts
- hosts:
    - localhost
  tags: ["always"]
  roles:
    - defaults

- hosts:
    - localhost
  roles:
    - image-registry/pull
    - image-registry/push