# In an online environment (when image_registry.auth.registry is empty), images are pulled directly from their original registries to the cluster.
# In an offline environment (when image_registry.auth.registry is set), images are first pulled from the source registry, cached locally, pushed to a private registry (such as Harbor), and then used by the cluster.

image_registry:
  # Specify which image registry to install. Supported values: harbor, docker-registry
  # If left empty, no image registry will be installed (assumes an existing registry is already available).
  type: ""
  ha_vip: ""
  # Directory where images to be pushed to the registry are stored.
  # Path for storing offline images
  images_dir: >- 
    {{ .tmp_dir }}/images/
  # Image registry authentication settings
  auth:
    registry: >-
      {{- if .image_registry.type | empty | not -}}
        {{- if .image_registry.ha_vip | empty | not -}}
      {{ .image_registry.ha_vip }}
        {{- else if .groups.image_registry | default list | empty | not -}}
          {{- $internalIPv4 := index .hostvars (.groups.image_registry | default list | first) "internal_ipv4" | default "" -}}
          {{- $internalIPv6 := index .hostvars (.groups.image_registry | default list | first) "internal_ipv6" | default "" -}}
          {{- if $internalIPv4 | empty | not -}}
      {{ $internalIPv4 }}
          {{- else if $internalIPv6 | empty | not -}}
      {{ $internalIPv6 }}
          {{- end -}}
        {{- end -}}
      {{- else -}}
        {{- if .zone | eq "cn" -}}
      hub.kubesphere.com.cn
        {{- end -}}
      {{- end -}}
    username: >-
      {{- if .zone | ne "cn" -}}
      admin
      {{- end -}}
    password: >-
      {{- if .zone | ne "cn" -}}
      Harbor12345
      {{- end -}}
    skip_tls_verify: >-
      {{- .image_registry.type | empty -}}
    ca_file: >-
      {{- if .groups.image_registry | default list | empty | not -}}
      {{ .binary_dir }}/pki/root.crt
      {{- end -}}
    cert_file: >-
      {{- if .groups.image_registry | default list | empty | not -}}
      {{ .binary_dir }}/pki/image_registry.crt
      {{- end -}}
    key_file: >-
      {{- if .groups.image_registry | default list | empty | not -}}
      {{ .binary_dir }}/pki/image_registry.key
      {{- end -}}
  # Registry endpoint for images from docker.io
  dockerio_registry: >-
    {{- .image_registry.auth.registry | empty | ternary "docker.io" .image_registry.auth.registry -}}

  # Registry endpoint for images from quay.io
  quayio_registry: >-
    {{- .image_registry.auth.registry | empty | ternary "quay.io" .image_registry.auth.registry -}}

  # Registry endpoint for images from ghcr.io
  ghcrio_registry: >-
    {{- .image_registry.auth.registry | empty | ternary "ghcr.io" .image_registry.auth.registry -}}

  # Registry endpoint for images from ghcr.io
  k8sio_registry: >-
    {{- .image_registry.auth.registry | empty | ternary "registry.k8s.io" .image_registry.auth.registry -}}
