download:
  # download timeout
  timeout: 300s
  # default cn zone file storage host
  cn_host: kubekey.pek3b.qingstor.com
  os: linux
  arch: [ "amd64" ]
  # offline artifact package for kk.
  artifact_file: ""
  # the md5_file of artifact_file.
  artifact_md5: ""
  # Whether to download software packages, Helm charts, container images, etc. online.
  # Set this to false if all required images and packages are already available locally and you do not need to validate against remote repositories.
  fetch: true
  artifact_url:
    # binary package
    etcd: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/etcd-io/etcd/releases/download/{{ "{{ .version }}" }}/etcd-{{ "{{ .version }}" }}-linux-{{ "{{ .arch }}" }}.tar.gz
    kubelet: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      dl.k8s.io/release/{{ "{{ .version }}" }}/bin/linux/{{ "{{ .arch }}" }}/kubelet
    kubeadm: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      dl.k8s.io/release/{{ "{{ .version }}" }}/bin/linux/{{ "{{ .arch }}" }}/kubeadm
    kubectl: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      dl.k8s.io/release/{{ "{{ .version }}" }}/bin/linux/{{ "{{ .arch }}" }}/kubectl
    cni_plugins: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/containernetworking/plugins/releases/download/{{ "{{ .version }}" }}/cni-plugins-linux-{{ "{{ .arch }}" }}-{{ "{{ .version }}" }}.tgz
    helm: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      get.helm.sh/helm-{{ "{{ .version }}" }}-linux-{{ "{{ .arch }}" }}.tar.gz
    crictl: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/kubernetes-sigs/cri-tools/releases/download/{{ "{{ .version }}" }}/crictl-{{ "{{ .version }}" }}-linux-{{ "{{ .arch }}" }}.tar.gz
    docker: >-
      https://mirrors.aliyun.com/docker-ce/linux/static/stable/
      {{- "{{ if eq .arch \"amd64\" }}x86_64{{ else if eq .arch \"arm64\" }}aarch64{{ end }}" -}}
      /docker-{{ "{{ .version }}" }}.tgz
    cridockerd: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/Mirantis/cri-dockerd/releases/download/{{ "{{ .version }}" }}/cri-dockerd-{{ "{{ .version | default \"\" | trimPrefix \"v\" }}" }}.{{ "{{ .arch }}" }}.tgz
    containerd: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/containerd/containerd/releases/download/{{ "{{ .version }}" }}/containerd-{{ "{{ .version | default \"\" | trimPrefix \"v\" }}" }}-linux-{{ "{{ .arch }}" }}.tar.gz
    runc: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/opencontainers/runc/releases/download/{{ "{{ .version }}" }}/runc.{{ "{{ .arch }}" }}
    calicoctl: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/projectcalico/calico/releases/download/{{ "{{ .version }}" }}/calicoctl-linux-{{ "{{ .arch }}" }}
    docker_registry: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      docker.io/registry/{{ "{{ .version }}" }}/docker-registry-{{ "{{ .version }}" }}-linux-{{ "{{ .arch }}" }}.tgz
    docker_compose: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/docker/compose/releases/download/{{ "{{ .version }}" }}/docker-compose-linux-
      {{- "{{ if eq .arch \"amd64\" }}x86_64{{ else if eq .arch \"arm64\" }}aarch64{{ end }}" -}}
    harbor: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/
      {{- "{{ if eq .arch \"amd64\" }}goharbor/harbor{{ else if eq .arch \"arm64\" }}kubesphere/kubekey{{ end }}" -}}
      /releases/download/
      {{- "{{ if eq .arch \"amd64\" }}{{ .version }}{{ else if eq .arch \"arm64\" }}iso-latest{{ end }}" -}}
      /harbor-offline-installer-{{ "{{ .version }}" }}.tgz
    keepalived: >-
      https://{{ .download.cn_host}}/osixia/keepalived/{{ "{{ .version }}" }}/keepalived-{{ "{{ .version }}" }}-linux-{{ "{{ .arch }}" }}.tgz
    # helm package
    calico: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/projectcalico/calico/releases/download/{{ "{{ .version }}" }}/tigera-operator-{{ "{{ .version }}" }}.tgz
    cilium: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      helm.cilium.io/cilium-{{ "{{ .version }}" }}.tgz
    flannel: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/flannel-io/flannel/releases/download/{{ "{{ .version }}" }}/flannel.tgz
    kubeovn: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      kubeovn.github.io/kube-ovn/kube-ovn-{{ "{{ .version }}" }}.tgz
    hybridnet: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/alibaba/hybridnet/releases/download/helm-chart-{{ "{{ .version }}" }}/hybridnet-{{ "{{ .version }}" }}.tgz
    localpv_provisioner: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      openebs.github.io/dynamic-localpv-provisioner/localpv-provisioner-{{ "{{ .version }}" }}.tgz
    nfs_subdir_external_provisioner: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/download/nfs-subdir-external-provisioner-{{ "{{ .version }}" }}/nfs-subdir-external-provisioner-{{ "{{ .version }}" }}.tgz
    spiderpool: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/spidernet-io/spiderpool/releases/download/{{ "{{ .version }}" }}/spiderpool-{{ "{{ .version | default \"\" | trimPrefix \"v\" }}" }}.tgz
  # tools will add to package
  tools:
    oras: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/oras-project/oras/releases/download/v1.3.0/oras_1.3.0_linux_{{ "{{ \"{{ .arch }}\" }}" }}.tar.gz
    nerdctl: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host}}/" .) "https://" -}}
      github.com/containerd/nerdctl/releases/download/v2.2.1/nerdctl-2.2.1-linux-{{ "{{ \"{{ .arch }}\" }}" }}.tar.gz
  charts: []
  # charts:
  #   # repo chart
  #   - url: flannel@https://flannel-io.github.io/flannel/
  #     version: 0.28.1
  #   # OCI chart
  #   - url: oci://ghcr.io/flannel-io/flannel-chart
  #     version: 0.28.1
  iso: 
    - "almalinux-9.0-rpms" 
    - "centos-8-rpms" 
    - "debian-10-debs" 
    - "debian-11-debs" 
    - "kylin-v10SP3-2403-rpms" 
    - "kylin-v10SP3-rpms" 
    - "kylin-v10SP2-rpms" 
    - "kylin-v10SP1-rpms" 
    - "ubuntu-18.04-debs" 
    - "ubuntu-20.04-debs" 
    - "ubuntu-22.04-debs" 
    - "ubuntu-24.04-debs"
  cni:
    type: []
  storage_class:
    local:
      enabled: true
    nfs:
      enabled: false
  cri:
    container_manager: >
      {{- $container_manager := list }}
      {{- range .download.kubernetes.kube_version }}
        {{- if and (. | semverCompare "<v1.24.0") ($container_manager | has "docker" | not) }}
          {{- $container_manager = append $container_manager "docker" }}
        {{- else if and (. | semverCompare ">=v1.24.0") ($container_manager | has "containerd" | not) }}
          {{- $container_manager = append $container_manager "containerd" }}
        {{- end }}
      {{- end }}
      {{- $container_manager | toJson }}

  images:
    manifests: []
    # Architectures for which images should be downloaded.
    registry: >
      {{- if .zone | eq "cn" }}
      hub.kubesphere.com.cn
      {{- end }}
    # Determines the image pull policy. support strict, warn
    policy: "strict"
    # kubernetes images list
    openebs-localpv/localpv-provisioner:
      "4.4.0":
        - docker.io/openebs/linux-utils:4.3.0
        - docker.io/openebs/provisioner-localpv:4.4.0
    nfs-subdir-external-provisioner/nfs-subdir-external-provisioner:
      "4.0.18":
        - registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
    projectcalico/tigera-operator:
      v3.25.2:
        - quay.io/tigera/operator:v1.29.6
        - docker.io/calico/apiserver:v3.25.2
        - docker.io/calico/cni:v3.25.2
        - docker.io/calico/csi:v3.25.2
        - docker.io/calico/ctl:v3.25.2
        - docker.io/calico/kube-controllers:v3.25.2
        - docker.io/calico/node-driver-registrar:v3.25.2
        - docker.io/calico/typha:v3.25.2
        - docker.io/calico/node:v3.25.2
        - docker.io/calico/pod2daemon-flexvol:v3.25.2
        - docker.io/flannel/flannel:v0.24.4
      v3.26.5:
        - quay.io/tigera/operator:v1.30.11
        - docker.io/calico/ctl:v3.26.5
        - docker.io/calico/typha:v3.26.5
        - quay.io/calico/node:v3.26.5
        - docker.io/calico/cni:v3.26.5
        - docker.io/calico/csi:v3.26.5
        - docker.io/calico/apiserver:v3.26.5
        - docker.io/calico/kube-controllers:v3.26.5
        - docker.io/calico/flannel-migration-controller:v3.26.5
        - docker.io/flannel/flannel:v0.24.4
        - docker.io/calico/dikastes:v3.26.5
        - docker.io/calico/node-driver-registrar:v3.26.5
        - quay.io/calico/pod2daemon-flexvol:v3.26.5
      v3.28.5:
        - quay.io/tigera/operator:v1.34.13
        - docker.io/calico/ctl:v3.28.5
        - docker.io/calico/typha:v3.28.5
        - quay.io/calico/node:v3.28.5
        # - docker.io/calico/node-windows:v3.28.5
        - docker.io/calico/cni:v3.28.5
        # - docker.io/calico/cni-windows:v3.28.5
        - docker.io/calico/csi:v3.28.5
        - docker.io/calico/apiserver:v3.28.5
        - docker.io/calico/kube-controllers:v3.28.5
        - docker.io/calico/flannel-migration-controller:v3.28.5
        - docker.io/flannel/flannel:v0.24.4
        - docker.io/calico/dikastes:v3.28.5
        - docker.io/calico/node-driver-registrar:v3.28.5
        - quay.io/calico/pod2daemon-flexvol:v3.28.5
      v3.29.7: # refer https://docs.tigera.io/calico/3.29/reference/component-versions
        - quay.io/tigera/operator:v1.36.16
        - docker.io/calico/ctl:v3.29.7
        - docker.io/calico/typha:v3.29.7
        - quay.io/calico/node:v3.29.7
        # - docker.io/calico/node-windows:v3.29.7
        - docker.io/calico/cni:v3.29.7
        # - docker.io/calico/cni-windows:v3.29.7
        - docker.io/calico/csi:v3.29.7
        - docker.io/calico/apiserver:v3.29.7
        - docker.io/calico/kube-controllers:v3.29.7
        - docker.io/calico/flannel-migration-controller:v3.29.7
        # - docker.io/calico/windows:v3.29.7
        - docker.io/flannel/flannel:v0.24.4
        - docker.io/calico/dikastes:v3.29.7
        - docker.io/calico/node-driver-registrar:v3.29.7
        - quay.io/calico/pod2daemon-flexvol:v3.29.7
      v3.30.5:
        - quay.io/tigera/operator:v1.38.9
        - docker.io/calico/ctl:v3.30.5
        - docker.io/calico/typha:v3.30.5
        - quay.io/calico/node:v3.30.5
        # - docker.io/calico/node-windows:v3.30.5
        - docker.io/calico/cni:v3.30.5
        # - docker.io/calico/cni-windows:v3.30.5
        - docker.io/calico/csi:v3.30.5
        - docker.io/calico/apiserver:v3.30.5
        - docker.io/calico/kube-controllers:v3.30.5
        - docker.io/calico/envoy-gateway:v3.30.5
        - docker.io/calico/envoy-proxy:v3.30.5
        - docker.io/calico/envoy-ratelimit:v3.30.5
        - docker.io/calico/flannel-migration-controller:v3.30.5
        - docker.io/flannel/flannel:v0.24.4
        - docker.io/calico/dikastes:v3.30.5
        - docker.io/calico/node-driver-registrar:v3.30.5
        - quay.io/calico/pod2daemon-flexvol:v3.30.5
        - docker.io/calico/csi:v3.30.5
        - docker.io/calico/key-cert-provisioner:v3.30.5
        - docker.io/calico/goldmane:v3.30.5
        - docker.io/calico/whisker:v3.30.5
        - docker.io/calico/whisker-backend:v3.30.5
      v3.31.3:
        - quay.io/tigera/operator:v1.40.3
        - quay.io/calico/ctl:v3.31.3
        - docker.io/calico/typha:v3.31.3
        - quay.io/calico/node:v3.31.3
        # - docker.io/calico/node-windows:v3.31.3
        - docker.io/calico/cni:v3.31.3
        # - docker.io/calico/cni-windows:v3.31.3
        - docker.io/calico/csi:v3.31.3
        - docker.io/calico/apiserver:v3.31.3
        - docker.io/calico/kube-controllers:v3.31.3
        - docker.io/calico/envoy-gateway:v3.31.3
        - docker.io/calico/envoy-proxy:v3.31.3
        - docker.io/calico/envoy-ratelimit:v3.31.3
        - docker.io/calico/flannel-migration-controller:v3.31.3
        - docker.io/flannel/flannel:v0.24.4
        - docker.io/calico/dikastes:v3.31.3
        - docker.io/calico/node-driver-registrar:v3.31.3
        - quay.io/calico/pod2daemon-flexvol:v3.31.3
        - docker.io/calico/csi:v3.31.3
        - docker.io/calico/key-cert-provisioner:v3.31.3
        - docker.io/calico/goldmane:v3.31.3
        - docker.io/calico/whisker:v3.31.3
        - docker.io/calico/whisker-backend:v3.31.3
    cilium/cilium:
      "1.14.19":
        - quay.io/cilium/cilium:v1.14.19
        - quay.io/cilium/clustermesh-apiserver:v1.14.19
        - quay.io/cilium/docker-plugin:v1.14.19
        - quay.io/cilium/hubble-relay:v1.14.19
        - quay.io/cilium/kvstoremesh:v1.14.19
        # - quay.io/cilium/operator-alibabacloud:v1.14.19
        # - quay.io/cilium/operator-aws:v1.14.19
        # - quay.io/cilium/operator-azure:v1.14.19
        - quay.io/cilium/operator-generic:v1.14.19
        - quay.io/cilium/operator:v1.14.19
      "1.15.19":
        - quay.io/cilium/cilium:v1.15.19
        - quay.io/cilium/clustermesh-apiserver:v1.15.19
        - quay.io/cilium/docker-plugin:v1.15.19
        - quay.io/cilium/hubble-relay:v1.15.19
        # - quay.io/cilium/operator-alibabacloud:v1.15.19
        # - quay.io/cilium/operator-aws:v1.15.19
        # - quay.io/cilium/operator-azure:v1.15.19
        - quay.io/cilium/operator:v1.15.19
      "1.16.18":
        - quay.io/cilium/cilium-envoy:v1.34.12-1765374555-6a93b0bbba8d6dc75b651cbafeedb062b2997716
        - quay.io/cilium/cilium:v1.16.18
        - quay.io/cilium/clustermesh-apiserver:v1.16.18
        - quay.io/cilium/docker-plugin:v1.16.18
        - quay.io/cilium/hubble-relay:v1.16.18
        # - quay.io/cilium/operator-alibabacloud:v1.16.18
        # - quay.io/cilium/operator-aws:v1.16.18
        # - quay.io/cilium/operator-azure:v1.16.18
        - quay.io/cilium/operator-generic:v1.16.18
        - quay.io/cilium/operator:v1.16.18
      "1.17.11":
        - quay.io/cilium/cilium-envoy:v1.34.12-1765374555-6a93b0bbba8d6dc75b651cbafeedb062b2997716 
        - quay.io/cilium/cilium:v1.17.11
        - quay.io/cilium/clustermesh-apiserver:v1.17.11
        - quay.io/cilium/docker-plugin:v1.17.11
        - quay.io/cilium/hubble-relay:v1.17.11
        # - quay.io/cilium/operator-alibabacloud:v1.17.11
        # - quay.io/cilium/operator-aws:v1.17.11
        # - quay.io/cilium/operator-azure:v1.17.11
        - quay.io/cilium/operator-generic:v1.17.11
        - quay.io/cilium/operator:v1.17.11
      "1.18.7":
        - quay.io/cilium/cilium-envoy:v1.35.9-1770554954-8ce3bb4eca04188f4a0a1bfbd0a06a40f90883de
        - quay.io/cilium/cilium:v1.18.7
        - quay.io/cilium/clustermesh-apiserver:v1.18.7
        - quay.io/cilium/docker-plugin:v1.18.7
        - quay.io/cilium/hubble-relay:v1.18.7
        # - quay.io/cilium/operator-alibabacloud:v1.18.7
        # - quay.io/cilium/operator-aws:v1.18.7
        # - quay.io/cilium/operator-azure:v1.18.7
        - quay.io/cilium/operator-generic:v1.18.7
        - quay.io/cilium/operator:v1.18.7
      "1.19.1":
        - quay.io/cilium/cilium-envoy:v1.35.9-1770979049-232ed4a26881e4ab4f766f251f258ed424fff663
        - quay.io/cilium/cilium:v1.19.1
        - quay.io/cilium/clustermesh-apiserver:v1.19.1
        - quay.io/cilium/docker-plugin:v1.19.1
        - quay.io/cilium/hubble-relay:v1.19.1
        # - quay.io/cilium/operator-alibabacloud:v1.19.1
        # - quay.io/cilium/operator-aws:v1.19.1
        # - quay.io/cilium/operator-azure:v1.19.1
        - quay.io/cilium/operator-generic:v1.19.1
        - quay.io/cilium/operator:v1.19.1
    flannel/flannel:
      v0.27.4:
        - ghcr.io/flannel-io/flannel-cni-plugin:v1.8.0-flannel1
        - ghcr.io/flannel-io/flannel:v0.27.4
    hybridnet/hybridnet:
      0.6.8:
        - docker.io/hybridnetdev/hybridnet:v0.8.8
    kubeovn/kube-ovn:
      v1.13.15:
        - docker.io/kubeovn/kube-ovn:v1.13.15
        - docker.io/kubeovn/vpc-nat-gateway:v1.13.15
      v1.15.0:
        - docker.io/kubeovn/kube-ovn:v1.15.0
        - docker.io/kubeovn/vpc-nat-gateway:v1.15.0
    spiderpool/spiderpool:
      v1.1.1:
        - ghcr.io/spidernet-io/spiderpool/spiderpool-plugins:27c4f118b1cec3773f2679b772e7583fc77e5686
        - ghcr.io/k8snetworkplumbingwg/multus-cni:v4.1.4
        - ghcr.io/spidernet-io/spiderpool/spiderpool-agent:v1.1.1
        - ghcr.io/spidernet-io/spiderpool/spiderpool-controller:v1.1.1