- name: OS | Add sudo secure path
  tags: ["always"]
  command: |
    ADD_PATHS="/usr/local/bin"
    echo "find current secure_path 配置"
    EXISTING_PATH=$(sudo sh -c 'echo $PATH')
    if [ -z "$EXISTING_PATH" ]; then
        echo "warning: can not get current secure_path, using defaults."
        EXISTING_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    fi

    echo "current secure_path: $EXISTING_PATH"
    NEW_PATH="$EXISTING_PATH"
    HAS_CHANGES=false
    IFS=':' read -ra PATHS_TO_ADD <<< "$ADD_PATHS"
    for path in "${PATHS_TO_ADD[@]}"; do
        [ -z "$path" ] && continue
        if [[ ":$NEW_PATH:" != *":$path:"* ]]; then
            NEW_PATH="$NEW_PATH:$path"
            HAS_CHANGES=true
        fi
    done
    
    if [ "$HAS_CHANGES" = true ]; then
        echo "new secure_path: $NEW_PATH"
        echo "Defaults secure_path=\"$NEW_PATH\"" > /etc/sudoers.d/99_z_k8s_secure_path
        chown root:root /etc/sudoers.d/99_z_k8s_secure_path
        chmod 440 /etc/sudoers.d/99_z_k8s_secure_path
    fi
    echo "success"