---
dependencies:
  - role: cni/calico
    when: .cni.type | eq "calico"

  - role: cni/cilium
    when: .cni.type | eq "cilium"

  - role: cni/flannel
    when: .cni.type | eq "flannel"

  - role: cni/kubeovn
    when: .cni.type | eq "kubeovn"

  - role: cni/hybridnet
    when: .cni.type | eq "hybridnet"

  - role: cni/multi-cni/multus
    when: .cni.multi_cni | eq "multus"

  - role: cni/multi-cni/spiderpool
    when: .cni.multi_cni | eq "spiderpool"