---
- name: Binary | Ensure etcd binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.etcd.etcd_version | default (list $.etcd.etcd_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when:
    - index (.item | default dict) "version" | empty | not
    - printf "%s/etcd/%s/%s/etcd-%s-linux-%s.tar.gz" .binary_dir .item.version .item.arch .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.etcd .item }}"
    dest: "{{ .binary_dir }}/etcd/{{ .item.version }}/{{ .item.arch }}/etcd-{{ .item.version }}-linux-{{ .item.arch }}.tar.gz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Kubernetes kubelet binaries are present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.kubernetes.kube_version | default (list $.kubernetes.kube_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - printf "%s/kube/%s/%s/kubelet" .binary_dir .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.kubelet .item }}"
    dest: "{{ .binary_dir }}/kube/{{ .item.version }}/{{ .item.arch }}/kubelet"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Kubernetes kubeadm binaries are present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.kubernetes.kube_version | default (list $.kubernetes.kube_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - printf "%s/kube/%s/%s/kubeadm" .binary_dir .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.kubeadm .item }}"
    dest: "{{ .binary_dir }}/kube/{{ .item.version }}/{{ .item.arch }}/kubeadm"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Kubernetes kubectl binaries are present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.kubernetes.kube_version | default (list $.kubernetes.kube_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - printf "%s/kube/%s/%s/kubectl" .binary_dir .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.kubectl .item }}"
    dest: "{{ .binary_dir }}/kube/{{ .item.version }}/{{ .item.arch }}/kubectl"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure CNI plugins are present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cni.cni_plugins_version | default (list $.cni.cni_plugins_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when:
    - index (.item | default dict) "version" | empty | not
    - printf "%s/cni/plugins/%s/%s/cni-plugins-linux-%s-%s.tgz" .binary_dir .item.version .item.arch .item.arch .item.version | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.cni_plugins .item }}"
    dest: "{{ .binary_dir }}/cni/plugins/{{ .item.version }}/{{ .item.arch }}/cni-plugins-linux-{{ .item.arch }}-{{ .item.version }}.tgz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Helm binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.kubernetes.helm_version | default (list $.kubernetes.helm_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when:
    - index (.item | default dict) "version" | empty | not
    - printf "%s/helm/%s/%s/helm-%s-linux-%s.tar.gz" .binary_dir .item.version .item.arch .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.helm .item }}"
    dest: "{{ .binary_dir }}/helm/{{ .item.version }}/{{ .item.arch }}/helm-{{ .item.version }}-linux-{{ .item.arch }}.tar.gz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure crictl binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cri.crictl_version | default (list $.cri.crictl_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when:
    - index (.item | default dict) "version" | empty | not
    - printf "%s/crictl/%s/%s/crictl-%s-linux-%s.tar.gz" .binary_dir .item.version .item.arch .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.crictl .item }}"
    dest: "{{ .binary_dir }}/crictl/{{ .item.version }}/{{ .item.arch }}/crictl-{{ .item.version }}-linux-{{ .item.arch }}.tar.gz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Docker binary is present
  tags: ["image_registry"]
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cri.docker_version | default (list $.cri.docker_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - >-
      or 
        (index (.download.image_registry | default dict) "type" | empty | not)
        (index (.image_registry | default dict) "type" | empty | not)
        ((index (.download.cri | default dict) "container_manager" | default (list .cri.container_manager)) | has "docker")
    - printf "%s/docker/%s/%s/docker-%s.tgz" .binary_dir .item.version .item.arch .item.version | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.docker .item }}"
    dest: "{{ .binary_dir }}/docker/{{ .item.version }}/{{ .item.arch }}/docker-{{ .item.version }}.tgz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure cri-dockerd binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cri.cridockerd_version | default (list $.cri.cridockerd_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - (index (.download.cri | default dict) "container_manager" | default (list .cri.container_manager)) | has "docker"
    - printf "%s/cri-dockerd/%s/%s/cri-dockerd-%s-%s.tgz" .binary_dir .item.version .item.arch (.item.version | trimPrefix "v") .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.cridockerd .item }}"
    dest: "{{ .binary_dir }}/cri-dockerd/{{ .item.version }}/{{ .item.arch }}/cri-dockerd-{{ .item.version | trimPrefix \"v\" }}-{{ .item.arch }}.tgz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure containerd binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cri.containerd_version | default (list $.cri.containerd_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - (index (.download.cri | default dict) "container_manager" | default (list .cri.container_manager)) | has "containerd"
    - printf "%s/containerd/%s/%s/containerd-%s-linux-%s.tar.gz" .binary_dir .item.version .item.arch (.item.version | trimPrefix "v") .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.containerd .item }}"
    dest: "{{ .binary_dir }}/containerd/{{ .item.version }}/{{ .item.arch }}/containerd-{{ .item.version | trimPrefix \"v\" }}-linux-{{ .item.arch }}.tar.gz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure runc binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cri.runc_version | default (list $.cri.runc_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - (index (.download.cri | default dict) "container_manager" | default (list .cri.container_manager)) | has "containerd"
    - printf "%s/runc/%s/%s/runc.%s" .binary_dir .item.version .item.arch .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.runc .item }}"
    dest: "{{ .binary_dir }}/runc/{{ .item.version }}/{{ .item.arch }}/runc.{{ .item.arch }}"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure calicoctl binary is present
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.cni.calico_version | default (list $.cni.calico_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - (index (.download.cni | default dict) "type" | default (list .cni.type)) | has "calico"
    - printf "%s/cni/calico/%s/%s/calicoctl-linux-%s" .binary_dir .item.version .item.arch .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.calicoctl .item }}"
    dest: "{{ .binary_dir }}/cni/calico/{{ .item.version }}/{{ .item.arch }}/calicoctl-linux-{{ .item.arch }}"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Docker Registry binary is present
  tags: ["image_registry"]
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.image_registry.docker_registry_version | default (list $.image_registry.docker_registry_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - (index (.download.image_registry | default dict) "type" | default (list .image_registry.type)) | has "docker-registry"
    - printf "%s/image-registry/docker-registry/%s/%s/docker-registry-%s-linux-%s.tgz" .binary_dir .item.version .item.arch .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.docker_registry .item }}"
    dest: "{{ .binary_dir }}/image-registry/docker-registry/{{ .item.version }}/{{ .item.arch }}/docker-registry-{{ .item.version }}-linux-{{ .item.arch }}.tgz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure docker-compose binary is present
  tags: ["image_registry"]
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.image_registry.dockercompose_version | default (list $.image_registry.dockercompose_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - or (index (.download.image_registry | default dict) "type" | empty | not) (.image_registry.type | empty | not)
    - printf "%s/image-registry/docker-compose/%s/%s/docker-compose" .binary_dir .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.docker_compose .item }}"
    dest: "{{ .binary_dir }}/image-registry/docker-compose/{{ .item.version }}/{{ .item.arch }}/docker-compose"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure Harbor binary is present
  tags: ["image_registry"]
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.image_registry.harbor_version | default (list $.image_registry.harbor_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - (index (.download.image_registry | default dict) "type" | default (list .image_registry.type)) | has "harbor"
    - printf "%s/image-registry/harbor/%s/%s/harbor-offline-installer-%s.tgz" .binary_dir .item.version .item.arch .item.version | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.harbor .item }}"
    dest: "{{ .binary_dir }}/image-registry/harbor/{{ .item.version }}/{{ .item.arch }}/harbor-offline-installer-{{ .item.version }}.tgz"
    timeout: "{{ .download.timeout }}"

- name: Binary | Ensure keepalived binary is present
  tags: ["image_registry"]
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $version := $.download.image_registry.keepalived_version | default (list $.image_registry.keepalived_version) }}
        {{- $result = append $result (dict "arch" $arch "version" $version) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - index (.item | default dict) "version" | empty | not
    - or (index (.download.image_registry | default dict) "type" | empty | not) (.image_registry.type | empty | not)
    - printf "%s/image-registry/keepalived/%s/%s/keepalived-%s-linux-%s.tgz" .binary_dir .item.version .item.arch .item.version .item.arch | fileExists | not
  http_get_file:
    url: "{{ tpl .download.artifact_url.keepalived .item }}"
    dest: "{{ .binary_dir }}/image-registry/keepalived/{{ .item.version }}/{{ .item.arch }}/keepalived-{{ .item.version }}-linux-{{ .item.arch }}.tgz"
    timeout: "{{ .download.timeout }}"