- name: Image | Download container images
  when:
    - .download.image.manifests | default list | empty | not
    - .download.image.fetch
  image:
    pull:
      platform: >-
        {{ .download.image.arch }}
      auths: "{{ .cri.registry.auths | toJson }}"
      images_dir: >-
        {{ .binary_dir }}/images/
      manifests: "{{ .download.image.manifests | toJson }}"
