---
- name: ISO | Download ISO files
  loop: >
    {{- $result := list -}}
    {{- range $arch := .download.arch }}
      {{- range $iso := $.download.iso }}
        {{- $result = append $result (dict "arch" $arch "iso" $iso) -}}
      {{- end }}
    {{- end }}
    {{- $result | toJson }}
  when: 
    - .download.iso | empty | not
    - printf "%s/repository/%s-%s.iso" .binary_dir .item.iso .item.arch | fileExists | not
  http_get_file:
    url: >-
      {{- .zone | eq "cn" | ternary (tpl "https://{{ .download.cn_host }}/" .) "https://" -}}
      github.com/kubesphere/kubekey/releases/download/iso-latest/{{ .item.iso }}-{{ .item.arch }}.iso
    dest: "{{ .binary_dir }}/repository/{{ .item.iso }}-{{ .item.arch }}.iso"
    timeout: "{{ .download.timeout }}"
